### ISSUE TITLE
New upstream with better events support

### ISSUE THREAD

**Issue by RogerHardiman** [rostislavzz/motion-onvif-events#1]
Hi
I have just merged some ONVIF events improvements into the upstream ONVIF library.
https://github.com/agsh/onvif/pull/127

Main changes are that events will pass through NAT now and it also supports the way Axis do ONVIF events with a Subscription ID.

If you could try the new upstream agsh onvif library that would be great.

Thanks
Roger

**Comment by rostislavzz** [comment]
https://github.com/rostislavzz/motion-onvif-events/releases/tag/v1.0.4
