### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MYeager1967** [rostislavzz/motion-onvif-events#4]
I would like to modify this to watch for a few other events and post to a URL when they occur. I'm trying to test some things out on my own but I'm unable to figure out how to do the NPM install from my local folder. It keeps throwing an error saying there's no package.json file when it's there. If you can tell me how to get past this, I'd appreciate it. Likewise, if you'd like to undertake adding to this, I'll give you my thoughts and you're free to see if you can make it work.

**Comment by rostislavzz** [comment]
Sorry for the long answer, I missed the notifications. You can run locally `node motion-onvif-events.js <arguments>`

**Comment by MYeager1967** [comment]
Not sure that I understand, but I'll play with it. 😀
